builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - 386
  - amd64
  - arm
  - arm64
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brew:
  github:
    owner: scottrigby
    name: homebrew-tap
  folder: Formula
  homepage:  https://github.com/scottrigby/simple-to-boost
  description: Go CLI tool to import a Simplenote bulk export into Boostnote
  test: |
    system "#{bin}/simple-to-boost"